name: Daily email

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 11 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: |-
        pip install -r requirements.txt
        pip install miniscrapes
    - name: Send the email
      env:
        MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
        MAILGUN_OUTGOING_DOMAIN: ${{ secrets.MAILGUN_OUTGOING_DOMAIN }}
        OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
        MINISCRAPES_TOML_FILES: ${{ secrets.MINISCRAPES_TOML_FILES }}
      run: |-
        mkdir tmp-toml/
        echo $MINISCRAPES_TOML_FILES | awk '/----------/{n++}{print >"tmp-toml/config" n ".toml" }'
        find . -name "tmp-toml/*.toml" -exec miniscrapes execute-scrapers --config-file {} \;
